Fix Caffe2 ONNX export
facebookresearch/detectron2 pull request #4153
Opened 2022-04-13 01:23 UTC by thiagocrepaldi

This PR fixes the `Caffe2Tracer.export_caffe2` API for the latest pytorch repo

It still depends on another fix on Pytorch repo and I will update the PR when I create it

2022-04-15 17:45 UTC, garymm requested changes
You can also add `Fixes #3488` to the PR description :-)

2022-04-15 17:45 UTC, garymm commented on detectron2/export/caffe2_export.py
>      passes = ["fuse_bn_into_conv"]
I'm pretty sure torch.onnx.export does this optimization so I think we can just remove onnxoptimizer entirely from this code:
https://cs.github.com/pytorch/pytorch/blob/9bb21fac9535f2eaec69f3c5bcf5617f7368b940/torch/csrc/jit/passes/onnx/eval_peephole.cpp#L39

2022-04-28 15:45 UTC, thiagocrepaldi commented
Depends on https://github.com/facebookresearch/detectron2/pull/4120 to leverage the ONNX check code below

```
from detectron2.utils.testing import is_onnx_installed
class TestCaffe2Export(unittest.TestCase):
    def setUp(self):
        if not is_onnx_installed():
            self.skipTest("ONNX is not installed")
```

2022-04-28 18:30 UTC, thiagocrepaldi commented
@garymm somehow I cannot request another review from you through GH's UI, but I have addressed your comments

2022-04-28 21:24 UTC, thiagocrepaldi commented
@FrancescoMandru @ppwwyyxx would appreciate your review if you got a chance

2022-04-28 22:04 UTC, garymm approved these changes

2022-04-28 22:04 UTC, garymm commented on tests/test_export_caffe2.py
>  class TestCaffe2Export(unittest.TestCase):
can you add another `@unittest.skipIf` instead of putting it inside setUp? Seems nice to be consistent.

2022-04-28 23:44 UTC, ppwwyyxx approved these changes
Caffe2's export path is considered deprecated. But I see no harm to include this fix. Thanks!

There seems to be a lint failure needs to be addressed

2022-04-29 14:24 UTC, thiagocrepaldi commented
> Caffe2's export path is considered deprecated. But I see no harm to include this fix. Thanks!
> 
> There seems to be a lint failure needs to be addressed

I appreciate you review. I've ran `./dev/linter.sh` and fixed an extra line between imports. Everything should be good now.
Thanks

2022-05-04 14:36 UTC, thiagocrepaldi commented
@ppwwyyxx could you approve the restricted workflow on this one too? Thanks

2022-05-04 21:04 UTC, thiagocrepaldi commented
@zhanghang1989 could help me with this internal failure? There are only warnings, but maybe it timed out?

2022-05-13 21:52 UTC, ppwwyyxx commented
FYI, there is no need to constantly rebase the PR on top of recent `main` branch, unless there is a conflict. The internal vcs will rebase automatically.

2022-05-16 18:34 UTC, ppwwyyxx commented
Just realized that there is a statement "This feature requires 1.9 > ONNX ≥ 1.6." in https://detectron2.readthedocs.io/en/latest/tutorials/deployment.html that will need to be updated

2022-05-16 19:56 UTC, thiagocrepaldi commented
> @thiagocrepaldi has updated the pull request. You must [reimport the pull request](https://www.internalfb.com/intern/opensource/github/pull_request/confirm/import/1103877913737300/) before landing.

No problem, just changed it to `This feature requires ONNX ≥ 1.6.`

2022-05-18 15:12 UTC, thiagocrepaldi commented
@zhanghang1989  is it expect for `Facebook Internal - Builds & Tests` pipeline to take more than 19h to complete? It is probably hanging in some test. Could you help me with that?

2022-05-23 20:29 UTC, closed without merging